name: Playwright Traffic (on-demand + scheduled)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'  # every hour (UTC) - edit or remove as needed

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1,2,3,4]   # parallel runners (each gets its own public IP). adjust length to scale.
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run Playwright simulator
        env:
          CONCURRENCY: 2   # number of parallel browser instances per runner
        run: |
          echo "Runner ${{ matrix.job }} starting"
          python main.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-logs-${{ matrix.job }}
          path: |
            **/*.log
            main.py
